Thuthikaran/habit-pulse

app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/pages/home.html.erb

I added some styles on the log in , sign up and forgot your password pages. Very modest styling , could do more changes in the future.

modified log in , sign up and forgot your password page

---

db/migrate/20240619183806_change_days_of_week_in_habits.rb
db/schema.rb

- changed habits.days_of_week from string to array of string
- the default value for this column is: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

fix: change days_of_week to array

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

Modified the application page so that i can work on the left side and pedro can work on the right side of the page.

started the application page and the index page

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

I've included several HTML elements, with some acting as placeholders. For instance, the username placeholder is there until we have seeded user data to display. Apart from that, everything else consists of HTML elements awaiting their respective features.

added some elements on the left side of the page

---

app/views/shared/_navbar.html.erb

feat: navbar title

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_score.scss
app/controllers/habit_statics_controller.rb
app/views/habit_statics/show.html.erb
config/routes.rb
db/migrate/20240624191255_add_default_to_occurrences.rb
db/schema.rb

- added migration to put total, missed and completed occurrences as 0 when no value is provided
-  added habit static show page with score result
- run `rails db:setup`

feat: habit static show basic func

---

db/seeds.rb

fix: seed habtis only in dev

---

app/views/pages/home.html.erb

-  A welcoming message
- A brief description of the app's purpose
- Basic styling 
- A button linking to the "About Us" page

styled the homepage

---

app/views/habits/index.html.erb
db/seeds.rb

- seed 2 habits for each user with 7 past occurrences marked completed or misssed

seed: 2 habits for each user with 7 passed occurrences

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_side_nav.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/layouts/application.html.erb

style app dashboard

---

app/controllers/habits_controller.rb
app/views/habits/index.html.erb
config/routes.rb

- Added a today action in HabitsController
- Updated view to list today's habits
- Updated routes for today's habits

Added today's habits feature

---

app/views/layouts/application.html.erb

- remove sidenav from landing page

fix: remove sidenav from landing page

---

app/assets/stylesheets/new_styles.scss
app/views/habits/new.html.erb
app/views/layouts/application.html.erb

Style buttons

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/new_styles.scss
app/views/habits/new.html.erb

- added general style to form-input & form-select

feat: style create form

---

app/views/habits/edit.html.erb

did some styling on the edit page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

- rename about us to try habit pulse
- change link to dashboard

fix: about us

---

app/models/habit.rb
app/views/habits/index.html.erb
app/views/habits/new.html.erb

Commented out the filter date option from the today's habit page.
Removed frequency and reminder options from the create form page.
Disabled frequency and reminder validation in the models page.
Commented out the current date from the create form page.
These changes temporarily remove unused features for cleaner UI and easier debugging.

Commented out

---

app/assets/stylesheets/pages/_dashboard.scss
app/assets/stylesheets/pages/_index.scss
app/views/dashboard/index.html.erb

- added message displaying number of current habits below welcome header
- if user have no habits, hide ring and today's habits completion

Dashboard display

---

app/controllers/habits_controller.rb
app/models/habit.rb
app/views/habits/_form.html.erb
db/seeds.rb

- Added end_date, frequency, and days_of_week fields to the habit creation form.
- Removed hard-coded habit frequency from the controller method, this was set to 'daily' always, now it's dynamic.
- Updated the create_occurrences method in the Habit model:
- Daily Habits: Automatically create one occurrence per day for a month.
- Weekly Habits: Automatically create one occurrence for the specified weekdays for 6 months.
- Commented out redundant duplication of the create_occurrences method. Keep as comment incased needed for DB seeding later.

form update

---

app/javascript/controllers/frequency_controller.js
app/javascript/controllers/index.js
app/views/habits/_form.html.erb

Implemented Stimulus controller to toggle visibility of days_of_week input based on frequency selection.
Input is hidden by default and then displays only when 'weekly' is selected.

Handling of days_of_week input toggling in habit create form

---

app/models/habit.rb

- add more categories to dropdown form

add more categories

---

app/models/habit.rb

- if days days_of_week or frequency is updated, future occurrences are regenerated
- it still mantains today's occurrence if it was already completed

fix: regenerate future occurrences on habit update based on new habit  frequency

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/config/_colors.scss
app/views/layouts/application.html.erb

Change the hover background color and text color for the 
- view habits button : line 57 
- view dashboard button : line 53 
on application.html.erb file 
the styles are being applied using the class btn-view 
on the application.scss file

Color change for the hover state 

---

app/javascript/controllers/datepicker_controller.js

display start date and end date in more human friendly

---

app/assets/stylesheets/components/_index.scss
app/views/habits/index.html.erb

line 34 on the index.htlml.erb

changed the styling a little for the actions button

---

db/seeds.rb

add user photo to seeds

---

app/controllers/application_controller.rb
app/views/errors/400.html.erb
app/views/errors/404.html.erb
app/views/errors/500.html.erb
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb

I added custom 400 and 500 error pages and also added flash message alerts for user notifications.

Add error pages and flash messages
